<a href="https://colab.research.google.com/github/MyhLantern/ML/blob/main/myh_yavandhasani_code_v1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from abc import ABC, abstractmethod

class MyhSparce(ABC):
    
    def compress_to_array(self):
      pass

    @abstractmethod
    def decompress_from_array(self):
      pass



In [ ]:
from abc import ABC, abstractmethod
import numpy as np
 
class Sparce(MyhSparce):        
    def __init__(self, spmatrix):
        self.sp_matrix = spmatrix
        self.efi_arr = []
        
    def compress_to_array(self):
      self.efi_arr = []
      
      for i in range(self.sp_matrix.shape[0]):
        for j in range(self.sp_matrix.shape[1]):
            if self.sp_matrix[i,j] != 0 :
              triplet = [i, j, self.sp_matrix[i][j]]
              self.efi_arr.append(triplet)  
      return self.efi_arr

    def decompress_from_array(self):
      sp_mat = np.array([[0. for x in range(self.sp_matrix.shape[0])] for z in range(self.sp_matrix.shape[1])])

      count = len(self.efi_arr)
      for i in range(count):
          sp_mat[self.efi_arr[i][0], self.efi_arr[i][1]] = self.efi_arr[i][2]
      return sp_mat



In [ ]:
import numpy as np
sparse_matrix = np.array([[0,0,7],[0,-5,0],[3,0,0]])

print('--------------------------------------------------------')
print('Main sparse matrix:')
print(sparse_matrix)

print('--------------------------------------------------------')
print('Compressed sparse matrix:')
mySp = Sparce(sparse_matrix)
efi_arr_ret = mySp.compress_to_array()
print(efi_arr_ret)

print('--------------------------------------------------------')
print('Decompressed sparse matrix:')
print(mySp.decompress_from_array())

--------------------------------------------------------
Main sparse matrix:
[[ 0  0  7]
 [ 0 -5  0]
 [ 3  0  0]]
--------------------------------------------------------
Compressed sparse matrix:
[[0, 2, 7], [1, 1, -5], [2, 0, 3]]
--------------------------------------------------------
Decompressed sparse matrix:
[[ 0.  0.  7.]
 [ 0. -5.  0.]
 [ 3.  0.  0.]]


In [ ]:
print('Test functionality of our class: ')


Test functionality of our class: 


In [ ]:
import unittest
import numpy as np

class TestSparce(unittest.TestCase):

    def test_sparse_compress_decompress(self):

        sparse_matrix = np.array([[0,0,0],[0,-5,0],[0,0,6]])
  
        mySp = Sparce(sparse_matrix)
        comp_ret = mySp.compress_to_array()
        decomp_ret = mySp.decompress_from_array()

        self.assertTrue(np.array_equal(sparse_matrix, decomp_ret))




In [ ]:
unittest.main(argv=[''], verbosity=2, exit=False)

test_sparse_compress_decompress (__main__.TestSparce) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.007s

OK
